name: PHP Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  php-syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check PHP syntax
  run: |
    echo "Демонстрация ошибочного запуска CI/CD"
    exit 1